
/**
 * edge function should populate the bucket with a json containing all the parkings with isInBlog checked. 
 * every parking should have its address, slug, coverImage, type of parking, max vehicle, name of the host and description.
 * the description should be max 200 characters and generated by calling gemini pro api. 
 * Inside this page, the json would be filtered based on the city CAP, so that only that specific city's parkings are shown.
 *  
 */


export default function page() {
    return (
        <div>CityPage</div>
    )
}